services:
  - type: web
    name: ware-arcade-game-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: PAYMENT_PROVIDER
        value: syncpay
      - key: SYNCPAY_TOKEN
        value: SEU_TOKEN_DA_SYNC_PAY
      - key: WEBHOOK_PATH
        value: /webhook/pix
      - key: AUTO_APPROVE_ON_PAID
        value: "1"
      - key: DATABASE_URL
        value: postgresql://neondb_owner:SUA_SENHA@ep-still-meadow-ackvlhau-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
